# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgis
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  schema_search_path: public

development:
  <<: *default
  # database: kb_development
  # kbtester copied back from staging server after post-processing 02Jun
  # use kbtester
  database: kbtester
  # database: kb_test

staging:
  <<: *default
  database: kb_edit
  # database: kindred-britain-stage
  password: <%= ENV['KB_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: kindred-britain-stage
  password: <%= ENV['KB_DATABASE_PASSWORD'] %>
